# Hey maintainer!
# Don't forget you can exclude individual examples using
# rubocop:disable RSpec/ExampleLength
# You're smarter than the machine!

AllCops:
  SuggestExtensions: false
  NewCops: enable
require:
  - rubocop-rspec

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
